# Feeling the heath: The California-Maricopa route, in search for affordable housing.

In this chapter, the aim is to analyze how regional migration flows from California have fostered the development of the Phoenix Metropolitan area. This region, located in Maricopa County on the Arizona desert heartland, is situated in close proximity to the Mexican border. We will provide evidence, based on Internal Revenue Service (IRS) records, to document another significant aspect of migration patterns: the flow of income across state borders.

In addition, we examine homelessness trends and policies addressing this critical social issue, often associated with housing affordability challenges, which hold particular significance for metropolitan areas in California and other urban areas across the country. 

## Data and methods. 

In this chapter, we conduct exploratory data analysis to illustrate supply-side factors and key challenges related to housing unaffordability, such as homelessness. Additionally, we uncover the significant effects of migration across state borders from the perspective of taxation and revenue in both the origin and destination metropolitan areas. Internal Revenue Service data provides an opportunity to quantify revenue losses in the origin metropolitan areas while demonstrating the positive contributions to the host area's economy.

The main source of information to achive this analysis comes from the Internal Revenue Service (IRS). In this conceptual strategy, Tax data represent a complementary view of population movements.  In order to approximate migration, the IRS records year-to-year address changes reported on individual income tax returns filed and documented by data on IRS Form 1040. 

In particular it records the number of residents that moved to a State or county and the origin from where they moved [@internalrevenueserviceMigrationDataUsers2021]. Data corresponds to calendar year 2020-2021, So it represents income earned during 2020. the most up to date information available at the moment of writing this book. 

According to the IRS,this data captures the situation prior to late September of each calendar year and represent between 95 and 98 percent of total annual filings[@internalrevenueserviceMigrationDataUsers2021], so it provides an arguably complete base scenario to evaluate this topic at a geographic suitable scale.
IN addition this source offers the age of the tax payer which is valuable to better understand migrants incomes profiles.


# Revenu landscapes for origin and destination metropolitan areas.

Considering population flows across state lines, the analysis indicates that California is the main contributor of out of state migration in the U.S. representing  one of three  or $30.4%$  of the total out of state IRS return filings.


