# The San Diego-Tijuana connection.

The housing market for Mexican cities at the US border has been attracting the attention of public policy officals and community organizations with a growing interest with particular emphasis after the 2009 financial crisis.  From the academic perspective several investigations have documented case studies where demand for residential space by population coming from the US[@kim2020emergence], are shaping the real state landscapes in the Mexican side.    

A behavior that in turn, creates a local upward path for housing prices on border urban areas on the Mexican side such as Tijuana, where local people facing higher housing prices are being priced-out of specific residential locations, including areas near the central business district (CBD) as well as the areas in close proximity to border crossings which face an increased pressure to accommodate a growing housing demand that customers and real estate investors coming from the north, create. 

Indeed, there exists empirical evidence documented by experts scholars on the field such as  Soto-Rubui and Hausman, [@SOTORUBIO201976] indicating that the local real estate market has experimented continuous pressures that has resulted in affordability challenges for residents in Mexican border cities such as Tijuana, where competition for residential space has intensified. 

In this chapter the goal is to analyze the economic conditions that explain the movement of people from the US into Mexican border cities. And it´s effects on real estate industry, in particular the chapter focuses on the biggest Mexican border city Tijuana. 

## Why Tijuana is important when studiying housing prices in California.

Tijuana, Baja California is located at the US Mexico border just across the city of San Diego. 
Given it´s privilege location, Tijuana has become the biggest population center in all of Mexico´s norther border and a strategic economic regional manufacture hub covering a wide range of industries, including electronics, automotive parts, medical devices, aerospace components, textiles, and consumer goods and services.

Notably, the historic influx of labor which has been robust since the 1970's is underpinned by a dynamic internal migration^[within the country] influx of individuals seeking livelihoods within the manufacturing sector[@kopinak2003globalization; @gallegosTijuanaBorderMigration2009], traditionally a low wage sector of the labor force[@kopinak2020wages]. Although this demographic trends were propelled by public policies dating back to 1965 with the emblematic  Border Industrialization Program (BIP) and bi national regulations such as the North American Free trade Agreement, (NAFTA) which was signed in December 1992, and subsequent USMCA (signed in November 2018), an intense trans border movement of people has developed overtime [@chavez2016border].

This city hosts the busiest pedestrian and personal Vehicle passenger port of entry to the US along the northern Mexican Border. 

According to official information provided by the Bureau of transportation statistics, during 2022, California ports of entry registered 16,104,055 pedestrian crossings and among these, the San Ysidro gate, situated right at Tijuana´s city heart, accounts for 6,678,157 pedestrian crossings, surpassing the traffic registered by second busiest port El Paso, by 82%.

[INSERT PLOT HER FOR WIAT TIMES AND TRAFFIC BY TYPE: EJ. PASSANGER VS. TRUCKS (COMMERCIAL ACTIVITY)]

This intense people movement reflects the underlying social dynamics that this region generates[@doi:10.1177/019791839603000407] which are strongly influenced by specific economic determinants, one such key driving factor being bi-national labor market conditions and housing market prices differentials.

Historically, there has been several structural factors that contribute to housing shortages in the Mexican city of Tijuana.[@SOTORUBIO201976], however recently, added pressures of binational economic nature, to enter the housing market have emerged, for the local population living in specific neighborhoods situated in close proximity to border crossings or residential areas that are particularly attractive to US commuters and remote workers coming from the San Diego area and the southern California region.


As a result, a surge in real estate development has occurred in the area known as Playas de Tijuana and Rosarito, where property prices have experienced rapid growth during the last decade. 
*!!!!!!! ATTENTION NEEDED HERE: data is needed to reinforce the argument. How house prices growth in this particular area compares to other urban areas in the country and to the average growth in the whole country?  INCLUDE DATA FOR MEXICNA REAL STATE PAGES SUCH AS INMUEBLES24 WITH COMPARATIVE TRENDS ANMONG THE MAIN CITIES*

